version: "3.9"

services:
  mkdocs-material:
    container_name: wiki
    image: jameslloyd/wiki
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/docs:/app/docs
      - ${PWD}/mkdocs.yml:/app/mkdocs.yml
    environment:
      - SITE_NAME=James Test With Env vars and Docker Compose
      - SITE_URL=http://localhost:8000
      - SITE_DESCRIPTION="This is some long description. This is some long description. This is some long description. This is some long description. This is some long description. This is some long description. This is some long description. This is some long description. This is some long description."
