version: "3.9"

services:
  hack-technicolor-docs:
    build: .
    container_name: wiki
    image: jameslloyd/wiki
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/app/docs
    environment:
      - SITE_NAME=James Test With Env vars and Docker Compose
      - SITE_URL=http://localhost:8000
      - SITE_DESCRIPTION="This is some long description. This is some long description. This is some long description. This is some long description. This is some long description. This is some long description. This is some long description. This is some long description. This is some long description."