site_name: !ENV SITE_NAME
site_url: !ENV SITE_URL
site_description: !ENV SITE_DESCRIPTION

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: preference
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs    
plugins: 
  - search